name: pull-request

# only run this workflow when the Dockerfile has changed

on:
  pull_request:
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: .githooks/pre-push
        run: .githooks/pre-push