name: publish

# run this workflow when the Dockerfile is modified on the main branch
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

# required by action-gh-release to create the tag / release in the repo
permissions:
  contents: write

jobs:
  publish:
    name: create a new release on GitHub and Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: calculate next release version
        id: vars
        run: |
          current_version="$(git tag | sort --version-sort | tail -n1)"
          current_version="${current_version:="-1"}"
          next_version="$(echo "$current_version + 1" | bc)"

          # see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#workflow
          echo "tag=$next_version" >> $GITHUB_OUTPUT
      
      - name: create Docker Hub image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            awwsmm/rust-ci:${{ steps.vars.outputs.tag }}
            awwsmm/rust-ci:latest
    
      - name: create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.vars.outputs.tag }}