name: publish

on:
    push:
      branches:
        - master

jobs:
  publish:
    name: publish container image to Docker Hub
    runs-on: ubuntu-22.04
    env:
      current_version: "${$(git tag | sort --version-sort | tail -n1):--1}"
      next_version: $(echo "$current_version + 1" | bc)

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $next_version,latest
    
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: $next_version