name: publish

# only run this workflow when the Dockerfile has changed

on:
    push:
      branches:
        - main
      paths:
        - Dockerfile

jobs:
  publish:
    name: publish container image to Docker Hub
    runs-on: ubuntu-22.04
    env:
      tag: $next_version

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          current_version="${$(git tag | sort --version-sort | tail -n1):--1}"
          next_version="$(echo "$current_version + 1" | bc)"
          echo "tag=$next_version" >> "$GITHUB_ENV"
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $tag,latest
    
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: $tag